API_KEY = "PKIW7PRBQM0V81UBAJIF"
API_SECRET = "hAI8OcHdSxnrCLchS7fZbfZHQHbac0MnvhGpzytv"

ALPACA_CONFIG = {
    "API_KEY": "PKIW7PRBQM0V81UBAJIF",
    "API_SECRET": "hAI8OcHdSxnrCLchS7fZbfZHQHbac0MnvhGpzytv",
    "PAPER": True
}